"""Build the per-sample CRoMa distribution floats.

  paper/sections/results_figure_distribution.tex        fig:croma-distribution  (\\input by results.tex)
  paper/sections/supp/figure_distributions.tex          fig:croma-distribution-tcga4x4,
                                                         fig:croma-distribution-tolkach (\\input by supp.tex)
  paper/sections/supp/figure_distribution_panda.tex     fig:croma-distribution-panda (\\input by supp/panda.tex)

Each caption describes the panel scope, ordering and visual encodings without narrating the
observed distributions (ADR-0010). The PDFs are drawn by
``scripts/repro/figures/croma_distribution_figure.py``
from the same runs, into each study directory rather than into ``paper/``; each float carries a
one-line copy instruction. No specific F(0)/LTM_10 numbers are printed here -- those live in the
results tables and prose, and a number never gets a second renderer.

Run: python scripts/repro/generate_distribution_floats.py
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from _distributions import (  # noqa: E402
    CAMELYON,
    CONTROL_MODEL,
    PANDA,
    SUPP_BENCHMARKS,
    assert_control_is_the_control,
    assert_no_natural_image_control,
    load,
)

FIGURE_OUT = Path("paper/sections/results_figure_distribution.tex")
SUPP_OUT = Path("paper/sections/supp/figure_distributions.tex")
PANDA_OUT = Path("paper/sections/supp/figure_distribution_panda.tex")

_HEADER = "% AUTO-GENERATED by scripts/repro/generate_distribution_floats.py -- do not edit by hand."


def _code(model: str) -> str:
    return rf"\code{{{model}}}"


def _source(entry) -> str:
    #: Built from the manifest, never spelled out: a literal ``output/metrics/<protocol>/``
    #: here would be a second source of truth for which run backs the paper (and the protocol
    #: guard in tests/test_paper_artifacts.py forbids it).
    return f"{entry.studies_rel}/plots/pdf/croma_distribution.pdf"


def _graphic(entry) -> str:
    #: The \includegraphics path, resolved by \graphicspath relative to paper/figures/.
    return f"results/{entry.benchmark}/pdf/croma_distribution.pdf"


def _fig_label(entry) -> str:
    #: The figure label mirrors the benchmark's results-table label, so a reader who lands on
    #: one finds the other by the same suffix (Camelyon collapses to the bare main label).
    return entry.label.replace("tab:main-results", "fig:croma-distribution")


def _figure_tex(entry, caption: str) -> str:
    """The figure environment, copy instruction and label shared by every distribution float."""
    source, graphic = _source(entry), _graphic(entry)
    return "\n".join([
        _HEADER,
        "% The PDF is drawn by scripts/repro/figures/croma_distribution_figure.py, into",
        f"% {source}.",
        f"% It is NOT staged: copy that file to paper/figures/{graphic} to resolve the",
        r"% \includegraphics below (\graphicspath reaches paper/figures/, not output/).",
        r"\begin{figure}[!htbp]",
        r"\centering",
        rf"\includegraphics[width=0.78\linewidth]{{{graphic}}}",
        caption,
        rf"\label{{{_fig_label(entry)}}}",
        r"\end{figure}",
    ]) + "\n"


def build_figure(dist) -> str:
    """The main-text Camelyon ridgeline."""
    assert_control_is_the_control(dist)

    caption = " ".join([
        r"\caption{\textbf{Per-sample \code{CRoMa} distributions on Camelyon.}",
        r"Ridgeline distributions for the \CamelyonRankedNModels{} pathology encoders and the",
        rf"natural-image control ({_code(CONTROL_MODEL)}),",
        r"ordered by median \code{CRoMa}. The dashed line denotes $\mcode{CRoMa}=0$, while",
        r"shading denotes the confounder-dominant region ($\mcode{CRoMa}<0$).",
    ]) + "}"

    return _figure_tex(CAMELYON, caption)


def build_supp_figure(entry, dist) -> str:
    """A supplementary ridgeline for TCGA-4x4 or Tolkach-ESCA."""
    assert_control_is_the_control(dist)

    n_models = rf"\{entry.prefix}RankedNModels{{}}"
    caption = " ".join([
        rf"\caption{{\textbf{{Per-sample \code{{CRoMa}} distributions on {entry.short_name}.}}",
        rf"Ridgeline distributions for {n_models} pathology encoders",
        rf"and the natural-image control ({_code(CONTROL_MODEL)}), ordered by pooled median.",
        r"The dashed line denotes $\mcode{CRoMa}=0$; shading denotes $\mcode{CRoMa}<0$.",
        rf"Per-model $F(0)$ and $\mcode{{LTM}}_{{10}}$ are reported in Table~\ref{{{entry.label}}}.",
    ]) + "}"

    return _figure_tex(entry, caption)


def build_supp(root: Path | None = None) -> str:
    """Both tile supplementary floats, in the order the paper presents them (Section 3.4)."""
    return "".join(build_supp_figure(entry, load(root, entry)) for entry in SUPP_BENCHMARKS)


def build_panda_figure(dist) -> str:
    """The slide-level PANDA ridgeline (supp:panda)."""
    assert_no_natural_image_control(dist)

    caption = " ".join([
        r"\caption{\textbf{\code{CRoMa} distributions on PCaBiop.}",
        r"Ridgeline distributions for the \PandaRankedNModels{}",
        r"slide-level encoders on PCaBiop, ordered by pooled median. The dashed line denotes",
        r"$\mcode{CRoMa}=0$; shading denotes $\mcode{CRoMa}<0$.",
        rf"Per-model $F(0)$ and $\mcode{{LTM}}_{{10}}$ are reported in Table~\ref{{{PANDA.label}}}.",
    ]) + "}"

    return _figure_tex(PANDA, caption)


def main() -> None:
    FIGURE_OUT.write_text(build_figure(load()))
    print(f"wrote {FIGURE_OUT}")
    SUPP_OUT.write_text(build_supp())
    print(f"wrote {SUPP_OUT}")
    PANDA_OUT.write_text(build_panda_figure(load(entry=PANDA)))
    print(f"wrote {PANDA_OUT}")


if __name__ == "__main__":
    main()
