"""Build the median-vs-tail Pareto floats.

  paper/sections/results_figure_pareto.tex   fig:croma-pareto            (\\input by results.tex)
  paper/sections/supp/figure_pareto.tex      fig:croma-pareto-tcga4x4,
                                             fig:croma-pareto-tolkach    (\\input by supp.tex)

Each caption defines the axes, frontier encoding and control exclusion without naming observed
leaders or interpreting the comparison (ADR-0010). The PDFs are drawn beside each run by
scripts/repro/figures/croma_pareto_figure.py, never into paper/; a one-line copy instruction
travels with each float. Mirrors generate_distribution_floats.py.

Run: python scripts/repro/generate_pareto_float.py
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from _distributions import (  # noqa: E402
    CAMELYON,
    SUPP_BENCHMARKS,
    assert_control_is_the_control,
    exposed_models,
    has_exposure_domain,
    load,
)
from _paper_tables import CaptionClaimError  # noqa: E402

FIGURE_OUT = Path("paper/sections/results_figure_pareto.tex")
SUPP_OUT = Path("paper/sections/supp/figure_pareto.tex")
_HEADER = "% AUTO-GENERATED by scripts/repro/generate_pareto_float.py -- do not edit by hand."


def _exposure_sentence(entry, exposed: frozenset[str]) -> str:
    """Render the domain-specific sentence for exactly the set the figure daggers."""
    if entry.benchmark == "pathorob-camelyon":
        (model,) = sorted(exposed)  # exactly one encoder on Camelyon; the sentence is singular
        return rf"$\dagger$ marks the Camelyon-exposed encoder (\code{{{model}}})."
    if entry.benchmark == "pathorob-tcga-4x4":
        return rf"$\dagger$ marks the {len(exposed)} TCGA-exposed encoders."
    if entry.benchmark == "pathorob-tolkach-esca":
        return (
            rf"$\dagger$ marks the {len(exposed)} RudolfV 2 encoders with possible "
            r"institutional/source-domain overlap: their disclosed training corpus includes "
            r"Charit\'e, and the scored CHA cohort is from Charit\'e. Exact patient or slide "
            r"overlap is unknown; the marker does not establish leakage."
        )
    raise CaptionClaimError(
        f"no exposure sentence for {entry.benchmark}; the figure marks a set the caption cannot "
        f"describe. Add a clause here, or clear the manifest's exposure_domain."
    )


def _exposure_clause(entry, dist) -> str:
    """The exposure sentence for a panel, or ``""`` when nothing on it is exposed.

    A benchmark whose scored cohorts overlap a pretraining domain (``has_exposure_domain``) MUST
    mark at least one encoder -- an empty set there means the mapping or the roster is broken, and
    a silent empty would drop the point-label daggers the figure is asked to draw. A benchmark with no
    such domain legitimately marks nothing, so it gets no sentence. The figure marks exactly
    ``exposed_models(...)``, so caption and figure agree by construction.
    """
    exposed = exposed_models(entry, dist)
    if has_exposure_domain(entry):
        if not exposed:
            raise CaptionClaimError(
                f"{entry.benchmark}: scored cohorts map to a pretraining domain but no roster "
                f"encoder is exposed; the exposure legend would mark nothing. Fix the metadata."
            )
    elif exposed:
        raise CaptionClaimError(
            f"{entry.benchmark}: has no exposure_domain yet exposed_models returned "
            f"{sorted(exposed)}; add a domain mapping so the caption can describe the marks."
        )
    return _exposure_sentence(entry, exposed) if exposed else ""


def _source(entry) -> str:
    #: Built from the manifest, never spelled out: a literal ``output/metrics/<protocol>/``
    #: here would be a second source of truth for which run backs the paper (and the protocol
    #: guard in tests/test_paper_artifacts.py forbids it).
    return f"{entry.studies_rel}/plots/pdf/croma_pareto.pdf"


def _graphic(entry) -> str:
    #: The \includegraphics path, resolved by \graphicspath relative to paper/figures/.
    return f"results/{entry.benchmark}/pdf/croma_pareto.pdf"


def _fig_label(entry) -> str:
    #: The figure label mirrors the benchmark's results-table label, so a reader who lands on
    #: one finds the other by the same suffix (Camelyon collapses to the bare main label).
    return entry.label.replace("tab:main-results", "fig:croma-pareto")


def _figure_tex(entry, caption: str) -> str:
    """The figure environment, copy instruction and label shared by every Pareto float."""
    source, graphic = _source(entry), _graphic(entry)
    return "\n".join([
        _HEADER,
        "% The PDF is drawn by scripts/repro/figures/croma_pareto_figure.py, into",
        f"% {source}.",
        f"% It is NOT staged: copy that file to paper/figures/{graphic} to resolve the",
        r"% \includegraphics below (\graphicspath reaches paper/figures/, not output/).",
        r"\begin{figure}[!htbp]",
        r"\centering",
        rf"\includegraphics[width=0.7\linewidth]{{{graphic}}}",
        caption,
        rf"\label{{{_fig_label(entry)}}}",
        r"\end{figure}",
    ]) + "\n"


def build_figure(dist) -> str:
    """The main-text Camelyon median-versus-tail float."""
    assert_control_is_the_control(dist)

    parts = [
        rf"\caption{{\textbf{{Median and lower-tail \code{{CRoMa}} on {CAMELYON.short_name}.}}",
        r"Median \code{CRoMa} is plotted against worst-decile mean $\mcode{LTM}_{10}$",
        r"for the \CamelyonRankedNModels{} pathology encoders evaluated in this study.",
        r"Higher values are preferable on both axes. Ringed points form the upper-right Pareto",
        r"frontier, while shaded points are dominated on both axes.",
        _exposure_clause(CAMELYON, dist),
    ]
    caption = " ".join(p for p in parts if p) + "}"

    return _figure_tex(CAMELYON, caption)


def build_supp_figure(entry, dist) -> str:
    """A supplementary Pareto float for TCGA-4x4 or Tolkach-ESCA.

    TCGA-4x4 marks its TCGA-exposed encoders; Tolkach-ESCA marks possible institutional exposure
    to its scored Charit\'e cohort without asserting patient- or slide-level overlap.
    """
    assert_control_is_the_control(dist)

    n_models = rf"\{entry.prefix}RankedNModels{{}}"
    parts = [
        rf"\caption{{\textbf{{Median and lower-tail \code{{CRoMa}} on {entry.short_name}.}}",
        rf"Pooled median \code{{CRoMa}} against worst-decile mean $\mcode{{LTM}}_{{10}}$ for the {n_models}",
        r"pathology encoders. Higher values are preferable on both axes. Ringed points form the",
        r"upper-right Pareto frontier, while shaded points are dominated on both axes.",
        rf"Per-model $F(0)$ and $\mcode{{LTM}}_{{10}}$ are reported in Table~\ref{{{entry.label}}}.",
        _exposure_clause(entry, dist),
    ]
    caption = " ".join(p for p in parts if p) + "}"

    return _figure_tex(entry, caption)


def build_supp(root: Path | None = None) -> str:
    """Both tile supplementary Pareto floats, in the order the paper presents them (Section 3.4)."""
    return "".join(build_supp_figure(entry, load(root, entry)) for entry in SUPP_BENCHMARKS)


def main() -> None:
    FIGURE_OUT.write_text(build_figure(load()))
    print(f"wrote {FIGURE_OUT}")
    SUPP_OUT.write_text(build_supp())
    print(f"wrote {SUPP_OUT}")


if __name__ == "__main__":
    main()
