"""Build the nIPD figures and downstream-correlation supplementary table."""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from _apd import Apd, FIGURE_DATASETS, load  # noqa: E402

FIGURE_OUT = Path("paper/sections/results_figure_apd.tex")
SUPP_FIGURE_OUT = Path("paper/sections/supp/figure_apd.tex")
TABLE_OUT = Path("paper/sections/supp/apd_correlation.tex")
PCABIOP_FIGURE_OUT = Path("paper/sections/supp/figure_apd_pcabiop.tex")

MAIN_FIGURE_DATASETS = ["camelyon"]
SUPP_FIGURE_DATASETS = ["tcga_4x4", "tolkach"]
GRAPHIC_SOURCE_DIR = "output/studies/apd/plots/pdf"
_HEADER = "% AUTO-GENERATED by scripts/repro/generate_apd_floats.py -- do not edit by hand."

_METRIC_ROWS = [
    (r"\textbf{\code{CRoMa}}", "Croma"),
    (r"\code{RI}", "Ri"),
    (r"\code{MaRI}", "Mari"),
]
_SCOPES = ("Camelyon", "Tcga", "Tolkach")


def _graphic(dataset: str) -> str:
    return f"croma_nipd_{dataset}.pdf"


def _fig_label(dataset: str) -> str:
    return "fig:croma-nipd-" + dataset.replace("_", "")


def _metric_block(reduction: str, regime: str, label: str) -> list[str]:
    lines = []
    for i, (row_label, metric) in enumerate(_METRIC_ROWS):
        lead = (
            rf"\multirow{{3}}{{*}}{{{label}}} & {row_label}"
            if i == 0
            else rf" & {row_label}"
        )
        cells = " & ".join(rf"\{reduction}{regime}{metric}{scope}" for scope in _SCOPES)
        lines.append(f"{lead} & {cells} " + r"\\")
    return lines


def _reference_row(regime: str, label: str) -> str:
    cells = " & ".join(rf"\Apd{regime}Croma{scope}" for scope in _SCOPES)
    return f"{label} & " + r"\textbf{\code{CRoMa}} & " + cells + r" \\"


def build_table(apd: Apd) -> str:
    apd.assert_control_excluded()
    caption = (
        r"\caption{\textbf{Per-benchmark association between representation robustness and "
        r"downstream shortcut susceptibility.} Spearman $\rho$ relates each representation "
        r"metric to normalized integrated performance degradation (\code{nIPD}), the primary "
        r"downstream reduction. Positive values indicate that more robust representations "
        r"undergo less degradation. The in-domain arm holds acquisition groups fixed and is "
        r"the primary mechanistic endpoint; the out-of-domain arm uses unseen acquisition "
        r"groups and additionally reflects distribution shift. Each benchmark contains "
        r"\ApdNModels{} ranked tile encoders. The final two rows "
        r"repeat the \code{CRoMa} analysis using PathoROB's original \code{APD} for continuity. "
        # PCaBiop is excluded from the correlation entirely -- five whole-slide encoders is too
        # few for a rank correlation to mean anything. This states the exclusion and stops
        # there: quoting its rho descriptively would report the very number the exclusion says
        # not to trust. The \Nipd*Pcabiop and \Pcabiop* macros stay in generated_values.tex,
        # unused by the manuscript, as the record of what was left out.
        r"PCaBiop contains only five whole-slide encoders, so we excluded it from the "
        r"correlation table.}"
    )
    return "\n".join(
        [
            _HEADER,
            r"\begin{table}[!htbp]",
            r"\centering",
            r"\small",
            r"\begin{tabular}{llccc}",
            r"\hline",
            " & Metric & " + " & ".join(apd.benchmark_labels()) + r" \\",
            r"\hline",
            *_metric_block("Nipd", "Id", r"\code{nIPD}$_\mathrm{ID}$"),
            r"\hline",
            *_metric_block("Nipd", "Ood", r"\code{nIPD}$_\mathrm{OOD}$"),
            r"\hline",
            _reference_row("Id", r"\code{APD}$_\mathrm{ID}$"),
            _reference_row("Ood", r"\code{APD}$_\mathrm{OOD}$"),
            r"\hline",
            r"\end{tabular}",
            caption,
            r"\label{tab:apd-correlation}",
            r"\end{table}",
        ]
    ) + "\n"


def _caption(dataset_label: str, n: int, *, supplementary: bool) -> str:
    title = (
        rf"\textbf{{\code{{CRoMa}} and \code{{nIPD}} on {dataset_label}.}}"
        if supplementary
        else rf"\textbf{{\code{{CRoMa}} against \code{{nIPD}} on {dataset_label}.}}"
    )
    tail = (
        r" Corresponding \code{RI}, \code{MaRI}, and legacy \code{APD} correlations are "
        r"reported in Table~\ref{tab:apd-correlation}."
        if supplementary
        else ""
    )
    return (
        rf"\caption{{{title} Columns show in-domain evaluation (left, acquisition groups "
        r"held fixed) and out-of-domain evaluation (right, unseen acquisition groups). "
        r"\textbf{Top row:} normalized performance change $g(V)$ relative to the "
        r"above-chance performance at $V=0$ as the training-set "
        rf"confounder--biology correlation increases to $V{{=}}1$; curves "
        rf"denote the ${n}$ tile encoders and error bars are 95\% $t$-intervals over "
        r"repeated training runs. \textbf{Bottom row:} pooled \code{CRoMa}$(m{=}5)$ versus "
        r"\code{nIPD}, one point per encoder. Dashed lines mark $g(V)=0$, "
        r"$\mcode{CRoMa}=0$ and "
        rf"$\mcode{{nIPD}}=0$.{tail}}}"
    )


def _figure_blocks(apd: Apd, datasets: list[str], *, supplementary: bool) -> str:
    labels = dict(zip(FIGURE_DATASETS, apd.benchmark_labels()))
    lines = [
        _HEADER,
        f"% PDFs are rendered under {GRAPHIC_SOURCE_DIR}/croma_nipd_<benchmark>.pdf.",
    ]
    for dataset in datasets:
        lines.extend(
            [
                r"\begin{figure}[!htbp]",
                r"\centering",
                rf"\includegraphics[width=0.92\linewidth]{{{_graphic(dataset)}}}",
                _caption(labels[dataset], apd.n_models, supplementary=supplementary),
                rf"\label{{{_fig_label(dataset)}}}",
                r"\end{figure}",
            ]
        )
    return "\n".join(lines) + "\n"


def build_pcabiop_figure() -> str:
    """Render the float for the descriptive five-encoder slide-level composite."""
    return "\n".join(
        [
            _HEADER,
            r"\begin{figure}[!htbp]",
            r"\centering",
            r"\includegraphics[width=0.92\linewidth]{croma_nipd_pcabiop.pdf}",
            (
                r"\caption{\textbf{\code{CRoMa} against \code{nIPD} on PCaBiop.} "
                r"Columns show in-domain evaluation on PANDA acquisition groups represented "
                r"during training (left) and out-of-domain evaluation on the held-out PAR "
                r"cohort (right). \textbf{Top row:} normalized performance change $g(V)$ "
                r"relative to the above-chance performance at $V=0$ as the training-set "
                r"confounder--biology correlation increases to $V=1$; curves denote the "
                r"five whole-slide encoders and error bars are 95\% $t$-intervals over "
                r"repeated training runs. \textbf{Bottom row:} pooled "
                r"\code{CRoMa}$(m{=}5)$ versus \code{nIPD}, one point per encoder. Dashed "
                r"lines mark $g(V)=0$, $\mcode{CRoMa}=0$ and $\mcode{nIPD}=0$. Spearman "
                r"coefficients are descriptive because the panel contains only $n=5$ "
                r"encoders.}"
            ),
            r"\label{fig:croma-nipd-pcabiop}",
            r"\end{figure}",
        ]
    ) + "\n"


def main() -> None:
    assert MAIN_FIGURE_DATASETS + SUPP_FIGURE_DATASETS == FIGURE_DATASETS
    apd = load()
    FIGURE_OUT.write_text(_figure_blocks(apd, MAIN_FIGURE_DATASETS, supplementary=False))
    SUPP_FIGURE_OUT.write_text(
        _figure_blocks(apd, SUPP_FIGURE_DATASETS, supplementary=True)
    )
    PCABIOP_FIGURE_OUT.write_text(build_pcabiop_figure())
    TABLE_OUT.write_text(build_table(apd))
    print(
        f"wrote {FIGURE_OUT}\n"
        f"wrote {SUPP_FIGURE_OUT}\n"
        f"wrote {PCABIOP_FIGURE_OUT}\n"
        f"wrote {TABLE_OUT}"
    )


if __name__ == "__main__":
    main()
