"""Build the CRoMa averaging-radius robustness table (tab:m-sweep).

Shows that model comparison is insensitive to the averaging radius ``m`` over the whole
sweep ``m in [1, 20]``. For each of the three PathoROB tile benchmarks (the same panel as
``fig:cross-benchmark``; imported from ``_cross_benchmark`` so there is one benchmark list)
it reports the Spearman correlation of the pooled-``CRoMa`` model rankings between the
headline radius ``m=5`` and each extreme (``m=1``, ``m=20``) and between the two extremes.

``build()`` also verifies -- but does not tabulate -- that the number of confounder-dominant
models (pooled ``CRoMa < 0``) is constant across the full sweep, the guard behind the prose
clause that increasing ``m`` leaves each model's dominant sign unchanged. The natural-image
control is excluded -- it is a floor, not a competitor, matching the ranked panel everywhere
else (CONTEXT.md, "ranked panel").

Run: python scripts/repro/generate_m_sweep_table.py
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
for _p in (REPO / "src", HERE):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import pandas as pd  # noqa: E402
from scipy.stats import spearmanr  # noqa: E402

from croma.metrics.croma import CROMA_HEADLINE_M  # noqa: E402
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts" / "bench"))  # noqa: E402  (plotting.style lives with the benchmark plot library)
from plotting.style import CONTROL_MODEL  # noqa: E402

from _cross_benchmark import PANEL, short_label  # noqa: E402
from paper_manifest import by_benchmark  # noqa: E402

OUT = Path("paper/sections/supp/m_sweep.tex")

#: The two extreme radii the ranking stress-test spans, and the headline in between.
M_LO, M_HEAD, M_HI = 1, int(CROMA_HEADLINE_M), 20


def _sweep(benchmark: str) -> pd.DataFrame:
    """Pooled CRoMa per (model, m) over the ranked panel, models x radii."""
    path = Path(f"{by_benchmark(benchmark).run_rel}/results/croma_m_sweep_metrics.csv")
    if not path.exists():
        raise FileNotFoundError(
            f"missing {path}; run the benchmark with the CRoMa m-sweep enabled first"
        )
    df = pd.read_csv(path)
    df = df[df["model"] != CONTROL_MODEL]
    return df.pivot(index="model", columns="m", values="croma")


def _rho(piv, a: int, b: int) -> float:
    return spearmanr(piv[a], piv[b]).statistic


def _row(benchmark: str) -> dict:
    piv = _sweep(benchmark)
    for m in (M_LO, M_HEAD, M_HI):
        if m not in piv.columns:
            raise ValueError(f"{benchmark}: m={m} not in the sweep {sorted(piv.columns)}")

    # The sign of each model's pooled CRoMa must not depend on m -- this guards the prose
    # clause that the averaging radius leaves the confounder-dominant set unchanged. Not
    # tabulated; a violation here means that sentence, not this table, needs rewording.
    dominant = {int(m): int((piv[m] < 0).sum()) for m in piv.columns}
    if len(set(dominant.values())) != 1:
        raise ValueError(
            f"{benchmark}: confounder-dominant count varies across the sweep ({dominant}); "
            f"the 'dominant sign is m-invariant' claim no longer holds on this panel"
        )
    return {
        "label": short_label(benchmark),
        "n": len(piv),
        "rho_lo_head": _rho(piv, M_LO, M_HEAD),
        "rho_head_hi": _rho(piv, M_HEAD, M_HI),
        "rho_lo_hi": _rho(piv, M_LO, M_HI),
    }


def build() -> str:
    rows = [_row(b) for b in PANEL]

    body = [
        f"\t\t{r['label']} & ${r['n']}$ & "
        rf"${r['rho_lo_head']:.3f}$ & ${r['rho_head_hi']:.3f}$ & ${r['rho_lo_hi']:.3f}$ \\"
        for r in rows
    ]

    caption = (
        r"\caption{\textbf{Robustness of \code{CRoMa} model comparison to the averaging "
        r"radius $m$.} For each of the three tile benchmarks, we report Spearman correlations "
        r"between the median $\mcode{CRoMa}$ model rankings at the headline radius $m=5$ and "
        r"each extreme ($m=1$, $m=20$), and between the two extremes.}"
    )

    return "\n".join([
        "% AUTO-GENERATED by scripts/repro/generate_m_sweep_table.py -- do not edit by hand.",
        r"\begin{table}[!htbp]",
        "\t" + r"\centering",
        "\t" + r"\begin{tabular}{lcccc}",
        "\t\t" + r"\hline",
        "\t\t" + rf"Benchmark & $n$ & $\rho(m{{=}}{M_LO},m{{=}}{M_HEAD})$ & "
        rf"$\rho(m{{=}}{M_HEAD},m{{=}}{M_HI})$ & $\rho(m{{=}}{M_LO},m{{=}}{M_HI})$ \\",
        "\t\t" + r"\hline",
        *body,
        "\t\t" + r"\hline",
        "\t" + r"\end{tabular}",
        "\t" + caption,
        "\t" + r"\label{tab:m-sweep}",
        r"\end{table}",
    ]) + "\n"


def main() -> None:
    OUT.write_text(build())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
