"""Build the APD floats: the per-dataset composite figures and the supplementary table.

  paper/sections/results_figure_apd.tex    fig:croma-apd-camelyon     (\\input by results_figures.tex)
  paper/sections/supp/figure_apd.tex       fig:croma-apd-{tcga4x4,tolkach} (\\input by supp.tex)
  paper/sections/supp/apd_correlation.tex  tab:apd-correlation        (\\input by supp.tex)

Each figure float is a 2x2 composite whose top row is linear-probe accuracy against Cramér's
$V$ and whose bottom row is the \\code{CRoMa}-vs-\\code{APD} scatter for one faithful tile
benchmark, split by regime (in-domain / out-of-domain). The Camelyon composite rides in the
main text as the exemplar (Section 3.5); the TCGA-4x4 and Tolkach-ESCA composites are demoted
to the supplement (supp:apd-benchmarks), reached by a pointer from the main text. Every
caption is computed from ``output/studies/apd/apd_correlation.csv``, and the table's cells
stay as ``\\Apd...`` macros so a number never has two renderers. The PDFs are drawn by
``scripts/repro/figures/apd_figure.py`` from the same study output, into the study directory
rather than into ``paper/``; the emitted float block carries the one-line copy instruction.

Run: python scripts/repro/generate_apd_floats.py
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from _apd import (  # noqa: E402
    Apd,
    load,
)
from loaders import HEADLINE_DATASETS  # noqa: E402

FIGURE_OUT = Path("paper/sections/results_figure_apd.tex")
SUPP_FIGURE_OUT = Path("paper/sections/supp/figure_apd.tex")
TABLE_OUT = Path("paper/sections/supp/apd_correlation.tex")

#: Which per-dataset APD composites ride in the main text versus the supplement. Camelyon is
#: the paper's primary benchmark throughout (Section 3), so it stays inline as the exemplar;
#: the other two faithful tile benchmarks are demoted to supp:apd-benchmarks, referenced from
#: the main text. Together these must partition HEADLINE_DATASETS (asserted in main()).
MAIN_FIGURE_DATASETS = ["camelyon"]
SUPP_FIGURE_DATASETS = ["tcga_4x4", "tolkach"]
#: Where ``apd_figure.py`` renders each per-dataset PDF, and where ``\includegraphics`` looks
#: for it. They differ on purpose: the figures are written beside their study data, and
#: nothing stages a copy into the manuscript tree (see the note on ``_out_stem`` in
#: ``apd_figure.py``). Copy them across by hand -- ``\graphicspath`` reaches
#: ``paper/figures/``, never ``output/``.
GRAPHIC_SOURCE_DIR = "output/studies/apd/plots/pdf"


def _graphic(ds: str) -> str:
    """Basename of the per-dataset composite, matching ``apd_figure._out_stem``."""
    return f"croma_apd_{ds}.pdf"


def _fig_label(ds: str) -> str:
    return "fig:croma-apd-" + ds.replace("_", "")

_HEADER = "% AUTO-GENERATED by scripts/repro/generate_apd_floats.py -- do not edit by hand."


#: The three metric rows within each APD block: (row label, macro infix). CRoMa's row label is
#: bold to flag it as the focus; the cells themselves are never bolded in this layout.
_METRIC_ROWS = [
    (r"\textbf{\code{CRoMa}}", "Croma"),
    (r"\code{RI}", "Ri"),
    (r"\code{MaRI}", "Mari"),
]
#: Scope suffixes, in column order, of the \Apd... macros generate_paper_values.py emits.
_SCOPES = ("Camelyon", "Tcga", "Tolkach", "Pooled")


def _apd_block(target: str, math: str) -> list[str]:
    """One \\code{APD}$_\\mathrm{ID/OOD}$ block: three \\multirow-led metric rows."""
    lines = []
    for i, (label, macro) in enumerate(_METRIC_ROWS):
        lead = (
            rf"\multirow{{3}}{{*}}{{\code{{APD}}$_\mathrm{{{math}}}$}} & {label}"
            if i == 0
            else rf" & {label}"
        )
        cells = " & ".join(rf"\Apd{target}{macro}{s}" for s in _SCOPES)
        lines.append(f"{lead} & {cells} " + r"\\")
    return lines


def build_table(apd: Apd) -> str:
    apd.assert_control_excluded()
    labels = apd.benchmark_labels()  # dashed short names: Camelyon, TCGA-4x4, Tolkach-ESCA
    caption = (
        r"\caption{\textbf{Correlation between representation robustness metrics and downstream "
        r"shortcut susceptibility}. Spearman $\rho$ across the \CamelyonRankedNModels{} pathology "
        r"encoders between the three robustness metrics (\code{RI}, \code{MaRI} and \code{CRoMa}) "
        r"and downstream shortcut susceptibility (\code{APD}). Correlations are reported for each "
        rf"benchmark, as well as computed jointly over all {apd.n_pairs} model--benchmark pairs "
        r"(\emph{pooled} column). Positive values indicate that larger robustness scores are "
        r"associated with smaller performance drops. \code{APD}$_\mathrm{ID}$ holds test centres "
        r"fixed. \code{APD}$_\mathrm{OOD}$ uses unseen centres. All three metrics track \code{APD} "
        r"comparably. Correlations weaken out of domain for all three, where \code{APD} "
        r"additionally reflects transfer to unseen confounders rather than shortcut reliance "
        r"alone.}"
    )
    header = " & Metric & " + " & ".join(labels) + r" & \emph{pooled} \\"

    return "\n".join([
        _HEADER,
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{llcccc}",
        r"\hline",
        header,
        r"\hline",
        *_apd_block("Id", "ID"),
        r"\hline",
        *_apd_block("Ood", "OOD"),
        r"\hline",
        r"\end{tabular}",
        caption,
        r"\label{tab:apd-correlation}",
        r"\end{table}",
    ]) + "\n"


def _main_caption(ds_label: str, n: int) -> str:
    """The main-text APD composite caption: the Camelyon exemplar (Section 3.5).

    Spelled out more fully than the supplementary version because it stands alone in the
    results text; the table it would cite is discussed in the same section.
    """
    return (
        rf"\caption{{\textbf{{\code{{CRoMa}} against \code{{APD}} on {ds_label}.}} "
        r"Columns show in-domain evaluation (left, test centres held fixed) and out-of-domain "
        r"evaluation (right, unseen centres). \textbf{Top row:} linear-probe accuracy on the "
        r"balanced test set as the centre--biology correlation in the training set increases "
        rf"from $V{{=}}0$ to $V{{=}}1$. Dashed curves denote the ${n}$ tile-level encoders and "
        r"error bars are 95\% confidence intervals over repeated seeding. \textbf{Bottom row:} "
        r"pooled \code{CRoMa}$(m{=}5)$ versus \code{APD}, one point per encoder. Dashed lines "
        r"mark $\mcode{CRoMa}=0$ and $\mcode{APD}=0$.}"
    )


def _supp_caption(ds_label: str, n: int) -> str:
    """The supplementary APD composite caption (TCGA-4x4 and Tolkach-ESCA)."""
    return (
        rf"\caption{{\textbf{{\code{{CRoMa}} and \code{{APD}} on {ds_label}.}} "
        r"Columns show in-domain evaluation (left; test centres held fixed) and out-of-domain "
        r"evaluation (right; unseen centres). \textbf{Top row,} balanced-test linear-probe "
        r"accuracy as the centre--biology correlation in the training set increases from "
        rf"$V{{=}}0$ to $V{{=}}1$; dashed curves denote the ${n}$ tile-level encoders and error "
        r"bars are 95\% $t$-intervals over seeds. \textbf{Bottom row,} pooled "
        r"\code{CRoMa}$(m{=}5)$ versus \code{APD}, one point per encoder. Dashed lines mark "
        r"$\mcode{CRoMa}=0$ and $\mcode{APD}=0$. Corresponding \code{RI} and \code{MaRI} "
        r"correlations are reported in Table~\ref{tab:apd-correlation}.}"
    )


def _figure_blocks(apd: Apd, datasets: list[str], intro: list[str], caption) -> str:
    """Emit one ``figure`` float per benchmark in ``datasets``, sharing one caption builder."""
    n = apd.n_models
    labels = dict(zip(HEADLINE_DATASETS, apd.benchmark_labels()))
    blocks = [_HEADER, *intro]
    for ds in datasets:
        blocks += [
            r"\begin{figure}[!htbp]",
            r"\centering",
            rf"\includegraphics[width=0.92\linewidth]{{{_graphic(ds)}}}",
            caption(labels[ds], n),
            rf"\label{{{_fig_label(ds)}}}",
            r"\end{figure}",
        ]
    return "\n".join(blocks) + "\n"


def build_figure(apd: Apd) -> str:
    """Main-text composite(s): the Camelyon exemplar (Section 3.5)."""
    apd.assert_control_excluded()
    intro = [
        "% Main-text APD composite: Camelyon only (the paper's primary benchmark). The",
        "% TCGA-4x4 and Tolkach-ESCA composites are demoted to supp/figure_apd.tex; the",
        "% split lives in generate_apd_floats.py (MAIN_FIGURE_DATASETS / SUPP_FIGURE_DATASETS).",
        "% The PDF is drawn by scripts/repro/figures/apd_figure.py into",
        f"% {GRAPHIC_SOURCE_DIR}/croma_apd_<benchmark>.pdf.",
        "% It is NOT staged: copy it to paper/figures/ to resolve the \\includegraphics",
        r"% below (\graphicspath reaches paper/figures/, not output/).",
    ]
    return _figure_blocks(apd, MAIN_FIGURE_DATASETS, intro, _main_caption)


def build_supp_figure(apd: Apd) -> str:
    """Supplementary composites: TCGA-4x4 and Tolkach-ESCA (supp:apd-benchmarks)."""
    intro = [
        "% Supplementary APD composites (supp:apd-benchmarks): the TCGA-4x4 and Tolkach-ESCA",
        "% benchmarks, demoted from the main text (Camelyon stays inline as the exemplar).",
        "% The PDFs are drawn by scripts/repro/figures/apd_figure.py into",
        f"% {GRAPHIC_SOURCE_DIR}/croma_apd_<benchmark>.pdf.",
        "% They are NOT staged: copy each to paper/figures/ to resolve the \\includegraphics",
        r"% below (\graphicspath reaches paper/figures/, not output/).",
    ]
    return _figure_blocks(apd, SUPP_FIGURE_DATASETS, intro, _supp_caption)


def main() -> None:
    assert MAIN_FIGURE_DATASETS + SUPP_FIGURE_DATASETS == HEADLINE_DATASETS, (
        "MAIN_FIGURE_DATASETS + SUPP_FIGURE_DATASETS must partition HEADLINE_DATASETS "
        f"({HEADLINE_DATASETS}); got {MAIN_FIGURE_DATASETS} + {SUPP_FIGURE_DATASETS}"
    )
    apd = load()
    FIGURE_OUT.write_text(build_figure(apd))
    SUPP_FIGURE_OUT.write_text(build_supp_figure(apd))
    TABLE_OUT.write_text(build_table(apd))
    print(f"wrote {FIGURE_OUT}\nwrote {SUPP_FIGURE_OUT}\nwrote {TABLE_OUT}")


if __name__ == "__main__":
    main()
