"""Build the rank-aggregate Pareto overview float (fig:croma-pareto-rank, supplement).

  paper/sections/supp/figure_rank_pareto.tex   fig:croma-pareto-rank   (\\input by supp.tex)

One overview figure that collapses the three per-benchmark Pareto panels into a single rank-based
view. The caption defines the axes and encodings without naming leaders or interpreting their
positions (ADR-0010). The PDF is drawn by
``scripts/repro/figures/rank_pareto_figure.py`` from the same loader; a one-line copy instruction
travels with the float. Mirrors generate_cross_benchmark_float.py.

Run: python scripts/repro/generate_rank_pareto_float.py
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from _rank_pareto import (  # noqa: E402
    assert_exposure_marked,
    load,
)

OUT = Path("paper/sections/supp/figure_rank_pareto.tex")
#: The \includegraphics path, resolved by \graphicspath relative to paper/; copy the rendered
#: PDF to paper/figures/rank_pareto.pdf. Mirrors generate_cross_benchmark_float.GRAPHIC.
GRAPHIC = "figures/rank_pareto.pdf"


def build() -> str:
    rp = load()
    exposed = assert_exposure_marked(rp)

    caption = " ".join([
        r"\caption{\textbf{Median and lower-tail \code{CRoMa} ranks across tile benchmarks.}",
        rf"Each of the {rp.n_benchmarks} tile benchmarks ranks the {rp.n_models} pathology encoders",
        r"by median \code{CRoMa} (rank $1$ = highest median) and by worst-decile mean",
        r"$\mcode{LTM}_{10}$ (rank $1$ = mildest tail). The axes show the mean rank across benchmarks,",
        r"with lower (=better) ranks plotted toward the upper-right corner. Ringed points form the",
        r"Pareto frontier, while shaded points are dominated on both axes.",
        rf"$\dagger$ marks the {len(exposed)} TCGA-exposed encoders.",
    ]) + "}"

    return "\n".join([
        "% AUTO-GENERATED by scripts/repro/generate_rank_pareto_float.py -- do not edit by hand.",
        "% The PDF is drawn by scripts/repro/figures/rank_pareto_figure.py, into",
        "% output/studies/rank-pareto/plots/pdf/rank_pareto.pdf.",
        r"% It is NOT staged: copy that file to paper/figures/rank_pareto.pdf to resolve the",
        r"% \includegraphics below (\graphicspath reaches paper/figures/, not output/).",
        r"\begin{figure}[!htbp]",
        r"\centering",
        rf"\includegraphics[width=0.7\linewidth]{{{GRAPHIC}}}",
        caption,
        r"\label{fig:croma-pareto-rank}",
        r"\end{figure}",
    ]) + "\n"


def main() -> None:
    OUT.write_text(build())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
